use_frameworks!

target 'ZZGridTextField_Example' do
  pod 'ZZGridTextField', :path => '../'

  target 'ZZGridTextField_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
