use_frameworks!

target 'ZZGridTextField_Example' do
  pod 'ZZGridTextField', :path => '../'

  target 'ZZGridTextField_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
